version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: dash-parse:0.1.0
    ports:
      - "8081:8080"
    networks:
      - dash-net
networks:
  dash-net:
    external: true

